TRY


In [3]:
import pandas as pd 
import numpy as np
from sklearn import decomposition 
import matplotlib.pyplot as plt

In [4]:
dataset = pd.read_csv("roo_data.csv")
dataset


Acedamic percentage in Operating Systems  percentage in Algorithms  \
0                                            69                        63   
1                                            78                        62   
2                                            71                        86   
3                                            76                        87   
4                                            92                        62   
...                                         ...                       ...   
19995                                        83                        67   
19996                                        80                        69   
19997                                        83                        70   
19998                                        68                        87   
19999                                        73                        77   

       Percentage in Programming Concepts  Percentage in Software Engineering  \
0                                      78                                  87   
1                                      73                                  60   
2                                      91                                  87   
3                                      60                                  84   
4                                      90                                  67   
...                                   ...                                 ...   
19995                                  62                                  63   
19996                                  83                                  87   
19997                                  80                                  87   
19998                                  91                                  88   
19999                                  74                                  84   

       Percentage in Computer Networks  Percentage in Electronics Subjects  \
0                                   94                                  94   
1                                   71                                  70   
2                                   61                                  81   
3                                   89                                  73   
4                                   71                                  89   
...                                ...                                 ...   
19995                               81                                  74   
19996                               82                                  66   
19997                               64                                  85   
19998                               66                                  74   
19999                               70                                  65   

       Percentage in Computer Architecture  Percentage in Mathematics  \
0                                       87                         84   
1                                       73                         84   
2                                       72                         72   
3                                       62                         88   
4                                       73                         71   
...                                    ...                        ...   
19995                                   90                         84   
19996                                   66                         92   
19997                                   69                         94   
19998                                   61                         87   
19999                                   92                         73   

       Percentage in Communication skills  Hours working per day  ...  \
0                                      61                      9  ...   
1                                      91                     12  ...   
2                                      94                     11  ...   
3  

In [4]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 39 columns):
 #   Column                                    Non-Null Count  Dtype 
---  ------                                    --------------  ----- 
 0   Acedamic percentage in Operating Systems  20000 non-null  int64 
 1   percentage in Algorithms                  20000 non-null  int64 
 2   Percentage in Programming Concepts        20000 non-null  int64 
 3   Percentage in Software Engineering        20000 non-null  int64 
 4   Percentage in Computer Networks           20000 non-null  int64 
 5   Percentage in Electronics Subjects        20000 non-null  int64 
 6   Percentage in Computer Architecture       20000 non-null  int64 
 7   Percentage in Mathematics                 20000 non-null  int64 
 8   Percentage in Communication skills        20000 non-null  int64 
 9   Hours working per day                     20000 non-null  int64 
 10  Logical quotient rating                   2000

In [5]:
unique_values = dataset['Interested Type of Books'].unique()
print(unique_values)

['Prayer books' 'Childrens' 'Travel' 'Romance' 'Cookbooks' 'Self help'
 'Drama' 'Math' 'Religion-Spirituality' 'Anthology' 'Trilogy'
 'Autobiographies' 'Mystery' 'Diaries' 'Journals' 'History' 'Art'
 'Dictionaries' 'Horror' 'Encyclopedias' 'Action and Adventure' 'Fantasy'
 'Comics' 'Science fiction' 'Series' 'Guide' 'Biographies' 'Health'
 'Satire' 'Science' 'Poetry']


In [6]:
unique_values = dataset['Type of company want to settle in?'].unique()
print(unique_values)

['Web Services' 'SAaS services' 'Sales and Marketing'
 'Testing and Maintainance Services' 'product development' 'BPA'
 'Service Based' 'Product based' 'Cloud Services' 'Finance']


In [ ]:
unique_values = dataset['Interested subjects'].unique()
print(unique_values)

['cloud computing' 'networks' 'hacking' 'Computer Architecture'
 'programming' 'parallel computing' 'IOT' 'data engineering'
 'Software Engineering' 'Management']


In [ ]:
unique_values = dataset['workshops'].unique()
print(unique_values)

['cloud computing' 'database security' 'web technologies' 'data science'
 'testing' 'hacking' 'game development' 'system designing']


In [7]:
dataset.values

array([[69, 63, 78, ..., 'yes', 'no', 'Database Developer'],
       [78, 62, 73, ..., 'no', 'yes', 'Portal Administrator'],
       [71, 86, 91, ..., 'no', 'yes', 'Portal Administrator'],
       ...,
       [83, 70, 80, ..., 'no', 'yes', 'Business Intelligence Analyst'],
       [68, 87, 91, ..., 'yes', 'no',
        'Software Quality Assurance (QA) / Testing'],
       [73, 77, 74, ..., 'yes', 'no', 'Applications Developer']],
      dtype=object)

In [9]:
data = dataset.iloc[:,:-1].values
label = dataset.iloc[:,-1].values
len(data[0])


38

In [10]:
dataset.iloc[:,14:38]

can work long time before system? self-learning capability?  \
0                                   yes                       yes   
1                                   yes                        no   
2                                   yes                        no   
3                                    no                       yes   
4                                    no                        no   
...                                 ...                       ...   
19995                               yes                        no   
19996                               yes                        no   
19997                               yes                       yes   
19998                                no                        no   
19999                               yes                       yes   

      Extra-courses did        certifications          workshops  \
0                   yes     shell programming    cloud computing   
1                   yes      machine learning  database security   
2                   yes       app development   web technologies   
3                    no                python       data science   
4                    no       app development    cloud computing   
...                 ...                   ...                ...   
19995                no       app development    cloud computing   
19996                no            full stack   game development   
19997               yes  information security  database security   
19998                no            full stack    cloud computing   
19999               yes       app development  database security   

      talenttests taken? olympiads reading and writing skills  \
0                     no       yes                  excellent   
1                     no        no                       poor   
2                     no       yes                       poor   
3                    yes        no                     medium   
4                     no        no                       poor   
...                  ...       ...                        ...   
19995                yes        no                       poor   
19996                 no       yes                     medium   
19997                yes       yes                     medium   
19998                 no       yes                       poor   
19999                 no       yes                  excellent   

      memory capability score    Interested subjects  ... interested in games  \
0                   excellent        cloud computing  ...                  no   
1                      medium               networks  ...                 yes   
2                   excellent                hacking  ...                 yes   
3                   excellent               networks  ...                  no   
4                   excellent  Computer Architecture  ...                 yes   
...                       ...                    ...  ...                 ...   
19995               excellent   Software Engineering  ...                 yes   
19996               excellent             Management  ...                 yes   
19997               excellent               networks  ...                 yes   
19998                    poor                    IOT  ...                  no   
19999               excellent                    IOT  ...                  no   

      Interested Type of Books Salary Range Expected In a Realtionship?  \
0                 Prayer books                salary                 no   
1                    Childrens                salary                yes   
2                       Travel                  Work                 no   
3                      Romance                  Work                yes   
4                    Cookbooks                salary                 no   
...                        ...                   ...                ...   
19995                 Journals                  Work                yes   
19996 

In [11]:
dataset.iloc[:,:14 ]

Acedamic percentage in Operating Systems  percentage in Algorithms  \
0                                            69                        63   
1                                            78                        62   
2                                            71                        86   
3                                            76                        87   
4                                            92                        62   
...                                         ...                       ...   
19995                                        83                        67   
19996                                        80                        69   
19997                                        83                        70   
19998                                        68                        87   
19999                                        73                        77   

       Percentage in Programming Concepts  Percentage in Software Engineering  \
0                                      78                                  87   
1                                      73                                  60   
2                                      91                                  87   
3                                      60                                  84   
4                                      90                                  67   
...                                   ...                                 ...   
19995                                  62                                  63   
19996                                  83                                  87   
19997                                  80                                  87   
19998                                  91                                  88   
19999                                  74                                  84   

       Percentage in Computer Networks  Percentage in Electronics Subjects  \
0                                   94                                  94   
1                                   71                                  70   
2                                   61                                  81   
3                                   89                                  73   
4                                   71                                  89   
...                                ...                                 ...   
19995                               81                                  74   
19996                               82                                  66   
19997                               64                                  85   
19998                               66                                  74   
19999                               70                                  65   

       Percentage in Computer Architecture  Percentage in Mathematics  \
0                                       87                         84   
1                                       73                         84   
2                                       72                         72   
3                                       62                         88   
4                                       73                         71   
...                                    ...                        ...   
19995                                   90                         84   
19996                                   66                         92   
19997                                   69                         94   
19998                                   61                         87   
19999                                   92                         73   

       Percentage in Communication skills  Hours working per day  \
0                                      61                      9   
1                                      91                     12   
2                                      94                     11   
3                      

In [12]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [13]:
labelencoder = LabelEncoder()

In [14]:
for i in range(14,38):
  data[:,i] = labelencoder.fit_transform(data[:,i])
data[:5]

array([[69, 63, 78, 87, 94, 94, 87, 84, 61, 9, 4, 0, 4, 8, 1, 1, 1, 8, 0,
        0, 1, 0, 0, 4, 4, 0, 8, 0, 0, 21, 1, 0, 1, 0, 0, 0, 1, 0],
       [78, 62, 73, 60, 71, 70, 73, 84, 91, 12, 7, 1, 2, 3, 1, 0, 1, 5,
        2, 0, 0, 2, 1, 7, 0, 1, 4, 1, 1, 5, 1, 1, 0, 1, 0, 0, 0, 1],
       [71, 86, 91, 87, 61, 81, 72, 72, 94, 11, 1, 4, 1, 3, 1, 0, 1, 0,
        7, 0, 1, 2, 0, 6, 2, 0, 5, 1, 1, 29, 0, 0, 1, 0, 1, 0, 0, 1],
       [76, 87, 60, 84, 89, 73, 62, 88, 69, 7, 1, 1, 2, 5, 0, 1, 0, 6, 1,
        1, 0, 1, 0, 7, 5, 0, 7, 0, 0, 23, 0, 1, 0, 0, 1, 1, 1, 1],
       [92, 62, 90, 67, 71, 89, 73, 71, 73, 4, 5, 4, 6, 3, 0, 0, 0, 0, 0,
        0, 0, 2, 0, 0, 5, 0, 9, 0, 1, 7, 1, 0, 1, 0, 1, 0, 1, 1]],
      dtype=object)

In [15]:
data[:5,14:]

array([[1, 1, 1, 8, 0, 0, 1, 0, 0, 4, 4, 0, 8, 0, 0, 21, 1, 0, 1, 0, 0,
        0, 1, 0],
       [1, 0, 1, 5, 2, 0, 0, 2, 1, 7, 0, 1, 4, 1, 1, 5, 1, 1, 0, 1, 0, 0,
        0, 1],
       [1, 0, 1, 0, 7, 0, 1, 2, 0, 6, 2, 0, 5, 1, 1, 29, 0, 0, 1, 0, 1,
        0, 0, 1],
       [0, 1, 0, 6, 1, 1, 0, 1, 0, 7, 5, 0, 7, 0, 0, 23, 0, 1, 0, 0, 1,
        1, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 5, 0, 9, 0, 1, 7, 1, 0, 1, 0, 1, 0,
        1, 1]], dtype=object)

In [16]:
from sklearn.preprocessing import Normalizer

In [17]:
data1 = data[:,:14]

In [18]:
normalized_data = Normalizer().fit_transform(data1)
print(normalized_data.shape)

(20000, 14)


In [20]:
normalized_data

array([[0.28508989, 0.26029947, 0.32227553, ..., 0.        , 0.01652695,
        0.0330539 ],
       [0.34997994, 0.27818918, 0.32754533, ..., 0.00448692, 0.00897384,
        0.01346077],
       [0.29501244, 0.35733901, 0.37811453, ..., 0.01662042, 0.0041551 ,
        0.01246531],
       ...,
       [0.3430836 , 0.28934762, 0.33068299, ..., 0.02480122, 0.00826707,
        0.01240061],
       [0.29479246, 0.37716094, 0.39450167, ..., 0.01734073, 0.03901665,
        0.02167592],
       [0.31140896, 0.32847247, 0.31567484, ..., 0.00426588, 0.02986113,
        0.02559526]])

In [19]:
normalized_data[1]

array([0.34997994, 0.27818918, 0.32754533, 0.26921534, 0.31857148,
       0.31408456, 0.32754533, 0.37690147, 0.40830993, 0.05384307,
       0.03140846, 0.00448692, 0.00897384, 0.01346077])

In [22]:
data2 = data[:,14:]
data2.shape

(20000, 24)

In [23]:
df1 = np.append(normalized_data,data2,axis = 1)

df1.shape

(20000, 38)

In [25]:
df1[1]

array([0.3499799388550931, 0.27818918216686883, 0.327545327390023,
       0.2692153375808408, 0.318571482803995, 0.314084560510981,
       0.327545327390023, 0.37690147261317714, 0.40830992866427523,
       0.053843067516168165, 0.0314084560510981, 0.004486922293014014,
       0.008973844586028028, 0.013460766879042041, 1, 0, 1, 5, 2, 0, 0, 2,
       1, 7, 0, 1, 4, 1, 1, 5, 1, 1, 0, 1, 0, 0, 0, 1], dtype=object)

## Adding header

In [27]:
X1 = pd.DataFrame(df1,columns=['Acedamic percentage in Operating Systems', 'percentage in Algorithms',
       'Percentage in Programming Concepts',
       'Percentage in Software Engineering', 'Percentage in Computer Networks',
       'Percentage in Electronics Subjects',
       'Percentage in Computer Architecture', 'Percentage in Mathematics',
       'Percentage in Communication skills', 'Hours working per day',
       'Logical quotient rating', 'hackathons', 'coding skills rating',
       'public speaking points', 'can work long time before system?',
       'self-learning capability?', 'Extra-courses did', 'certifications',
       'workshops', 'talenttests taken?', 'olympiads',
       'reading and writing skills', 'memory capability score',
       'Interested subjects', 'interested career area ', 'Job/Higher Studies?',
       'Type of company want to settle in?',
       'Taken inputs from seniors or elders', 'interested in games',
       'Interested Type of Books', 'Salary Range Expected',
       'In a Realtionship?', 'Gentle or Tuff behaviour?',
       'Management or Technical', 'Salary/work', 'hard/smart worker',
       'worked in teams ever?', 'Introvert'])

In [28]:
X1.head()

Acedamic percentage in Operating Systems percentage in Algorithms  \
0                                  0.28509                 0.260299   
1                                  0.34998                 0.278189   
2                                 0.295012                 0.357339   
3                                 0.328025                 0.375503   
4                                 0.397157                 0.267649   

  Percentage in Programming Concepts Percentage in Software Engineering  \
0                           0.322276                           0.359461   
1                           0.327545                           0.269215   
2                           0.378115                           0.361494   
3                           0.258967                           0.362554   
4                           0.388523                           0.289234   

  Percentage in Computer Networks Percentage in Electronics Subjects  \
0                        0.388383                           0.388383   
1                        0.318571                           0.314085   
2                        0.253461                           0.336563   
3                        0.384135                           0.315077   
4                        0.306502                           0.384206   

  Percentage in Computer Architecture Percentage in Mathematics  \
0                            0.359461                  0.347066   
1                            0.327545                  0.376901   
2                            0.299168                  0.299168   
3                              0.2676                  0.379819   
4                            0.315136                  0.306502   

  Percentage in Communication skills Hours working per day  ...  \
0                           0.252036              0.037186  ...   
1                            0.40831              0.053843  ...   
2                            0.39058              0.045706  ...   
3                           0.297812              0.030213  ...   
4                           0.315136              0.017268  ...   

  interested in games Interested Type of Books Salary Range Expected  \
0                   0                       21                     1   
1                   1                        5                     1   
2                   1                       29                     0   
3                   0                       23                     0   
4                   1                        7                     1   

  In a Realtionship? Gentle or Tuff behaviour? Management or Technical  \
0                  0                         1                       0   
1                  1                         0                       1   
2                  0                         1                       0   
3                  1                         0                       0   
4                  0                         1                       0   

  Salary/work hard/smart worker worked in teams ever? Introvert  
0           0                 0                     1         0  
1           0                 0                     0         1  
2           1                 0                     0         1  
3           1                 1                     1         1  
4           1                 0                     1         1  

[5 rows x 38 columns]

In [29]:
X1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 38 columns):
 #   Column                                    Non-Null Count  Dtype 
---  ------                                    --------------  ----- 
 0   Acedamic percentage in Operating Systems  20000 non-null  object
 1   percentage in Algorithms                  20000 non-null  object
 2   Percentage in Programming Concepts        20000 non-null  object
 3   Percentage in Software Engineering        20000 non-null  object
 4   Percentage in Computer Networks           20000 non-null  object
 5   Percentage in Electronics Subjects        20000 non-null  object
 6   Percentage in Computer Architecture       20000 non-null  object
 7   Percentage in Mathematics                 20000 non-null  object
 8   Percentage in Communication skills        20000 non-null  object
 9   Hours working per day                     20000 non-null  object
 10  Logical quotient rating                   2000

In [30]:
label = labelencoder.fit_transform(label)
print(len(label))

20000


In [31]:
y = pd.DataFrame(label,columns = ["Suggested Job Role"])
y.head()

Suggested Job Role
0                   7
1                  18
2                  18
3                  28
4                   2

In [32]:
y.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 1 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Suggested Job Role  20000 non-null  int64
dtypes: int64(1)
memory usage: 156.4 KB


### **Decision Tree Classifier**

In [33]:
from sklearn import tree
from sklearn.model_selection import train_test_split
from sklearn import preprocessing 
from sklearn.metrics import accuracy_score

In [34]:
X_train,X_test,y_train,y_test=train_test_split(X1,y,test_size=0.2,random_state=10) 

In [35]:
clf = tree.DecisionTreeClassifier()
clf = clf.fit(X_train, y_train)

In [36]:
from sklearn.metrics import confusion_matrix,accuracy_score

In [37]:
y_pred = clf.predict(X_test)

In [38]:
y_pred

array([27, 20,  5, ..., 23, 29, 28])

In [39]:
cm = confusion_matrix(y_test,y_pred)
accuracy = accuracy_score(y_test,y_pred)

In [42]:
print("confusion matrics=",cm)
print("  ")
print("accuracy=",accuracy*100)

confusion matrics= [[4 7 4 ... 5 6 3]
 [3 1 2 ... 6 1 5]
 [1 2 2 ... 4 1 5]
 ...
 [4 3 2 ... 2 0 6]
 [3 3 1 ... 3 5 5]
 [2 4 2 ... 3 2 2]]
  
accuracy= 2.725


# **Decision tree with entropy**

In [43]:
clf_entropy = tree.DecisionTreeClassifier(criterion = "entropy", random_state = 10)
clf_entropy.fit(X_train, y_train)

DecisionTreeClassifier(criterion='entropy', random_state=10)

In [44]:
entropy_y_pred=clf_entropy.predict(X_test)

In [45]:
cm_entopy = confusion_matrix(y_test,entropy_y_pred)

In [46]:
entropy_accuracy = accuracy_score(y_test,entropy_y_pred)

In [47]:
print("confusion matrics=",cm_entopy)
print("  ")
print("accuracy=",entropy_accuracy*100)

confusion matrics= [[1 3 7 ... 3 2 2]
 [2 4 3 ... 3 2 4]
 [1 2 4 ... 0 3 1]
 ...
 [1 6 3 ... 0 5 2]
 [3 2 4 ... 2 2 4]
 [5 1 6 ... 6 6 4]]
  
accuracy= 2.7


SVM(Support Vector Machine) Classifier
## **New Section**

In [48]:
from sklearn import svm

In [49]:
clf = svm.SVC()
clf.fit(X_train, y_train)

/usr/local/lib/python3.9/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC()

In [50]:
svm_y_pred = clf.predict(X_test)

In [51]:
svm_cm = confusion_matrix(y_test,svm_y_pred)
svm_accuracy = accuracy_score(y_test,svm_y_pred)

In [52]:
print("confusion matrics=",svm_cm)
print("  ")
print("accuracy=",svm_accuracy*100)

confusion matrics= [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
  
accuracy= 5.6000000000000005


## **XgBoost**

## **Changing data type to int64**

In [53]:
X_train,X_test,y_train,y_test=train_test_split(X1,y,test_size=0.3,random_state=10) 

In [54]:
X_train.shape

(14000, 38)

In [55]:
X_train = pd.to_numeric(X_train.values.flatten())

In [56]:
X_train = X_train.reshape((14000,38))

In [57]:
from xgboost import XGBClassifier

In [58]:
model = XGBClassifier()
model.fit(X_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              n_estimators=100, n_jobs=None, num_parallel_tree=None,
              objective='multi:softprob', predictor=None, ...)

In [59]:
xgb_y_pred = clf.predict(X_test)

In [63]:
xgb_cm = confusion_matrix(y_test,xgb_y_pred)
xgb_accuracy = accuracy_score(y_test,xgb_y_pred)


In [64]:
print("confusion matrics=",xgb_cm)
print("  ")
print("accuracy=",xgb_accuracy*100)

confusion matrics= [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
  
accuracy= 5.75


### exporting Data


In [ ]:
import pickle

pickle.dump(dataset,open('dataset.pkl','wb'))
pickle.dump(clf,open('clf.pkl','wb'))

In [66]:
import pickle

pickle.dump(dataset,open('dataset.pkl','wb'))
pickle.dump(clf,open('xgb_y_pred.pkl','wb'))

In [ ]:
dataset


Acedamic percentage in Operating Systems  percentage in Algorithms  \
0                                            69                        63   
1                                            78                        62   
2                                            71                        86   
3                                            76                        87   
4                                            92                        62   
...                                         ...                       ...   
19995                                        83                        67   
19996                                        80                        69   
19997                                        83                        70   
19998                                        68                        87   
19999                                        73                        77   

       Percentage in Programming Concepts  Percentage in Software Engineering  \
0                                      78                                  87   
1                                      73                                  60   
2                                      91                                  87   
3                                      60                                  84   
4                                      90                                  67   
...                                   ...                                 ...   
19995                                  62                                  63   
19996                                  83                                  87   
19997                                  80                                  87   
19998                                  91                                  88   
19999                                  74                                  84   

       Percentage in Computer Networks  Percentage in Electronics Subjects  \
0                                   94                                  94   
1                                   71                                  70   
2                                   61                                  81   
3                                   89                                  73   
4                                   71                                  89   
...                                ...                                 ...   
19995                               81                                  74   
19996                               82                                  66   
19997                               64                                  85   
19998                               66                                  74   
19999                               70                                  65   

       Percentage in Computer Architecture  Percentage in Mathematics  \
0                                       87                         84   
1                                       73                         84   
2                                       72                         72   
3                                       62                         88   
4                                       73                         71   
...                                    ...                        ...   
19995                                   90                         84   
19996                                   66                         92   
19997                                   69                         94   
19998                                   61                         87   
19999                                   92                         73   

       Percentage in Communication skills  Hours working per day  ...  \
0                                      61                      9  ...   
1                                      91                     12  ...   
2                                      94                     11  ...   
3  

In [ ]:
X_train

Acedamic percentage in Operating Systems percentage in Algorithms  \
18660                                 0.332394                 0.386408   
10831                                 0.355273                 0.359887   
5511                                  0.378435                 0.291104   
3543                                  0.289874                 0.353817   
12340                                 0.293294                 0.288712   
...                                        ...                      ...   
9372                                  0.317882                 0.385697   
7291                                  0.331845                 0.335573   
17728                                 0.352283                 0.289375   
7293                                  0.344894                 0.319658   
17673                                 0.370622                 0.382976   

      Percentage in Programming Concepts Percentage in Software Engineering  \
18660                           0.353169                           0.265915   
10831                           0.415254                           0.276836   
5511                            0.311897                           0.324373   
3543                            0.289874                            0.26856   
12340                           0.417028                           0.389531   
...                                  ...                                ...   
9372                            0.267021                           0.381459   
7291                            0.350488                           0.328116   
17728                           0.293569                           0.385833   
7293                            0.319658                           0.336482   
17673                           0.358267                           0.341795   

      Percentage in Computer Networks Percentage in Electronics Subjects  \
18660                        0.353169                              0.295   
10831                        0.350659                           0.341431   
5511                         0.345166                           0.307738   
3543                         0.383657                           0.302662   
12340                        0.274963                           0.274963   
...                               ...                                ...   
9372                         0.398412                           0.309405   
7291                         0.305745                           0.346759   
17728                        0.385833                           0.285181   
7293                         0.311246                           0.298628   
17673                        0.317087                            0.37474   

      Percentage in Computer Architecture Percentage in Mathematics  \
18660                            0.340704                  0.282535   
10831                            0.276836                  0.309133   
5511                             0.295262                  0.378435   
3543                             0.323977                  0.383657   
12340                            0.293294                  0.334539   
...                                   ...                       ...   
9372                              0.27126                  0.330598   
7291                             0.320659                  0.324388   
17728                            0.280987                  0.369058   
7293                             0.353306                  0.332276   
17673                            0.284143                  0.280025   

      Percentage in Communication skills Hours working per day  ...  \
18660                           0.365633              0.033239  ...   
10831                           0.286064              0.018456  ...   
5511                            0.349324              0.049903  ...   
3543                            0.375131              0.017051  ...   
12340                           0.3

In [ ]:
y_train

Suggested Job Role
18660                  16
10831                   4
5511                   28
3543                   11
12340                   3
...                   ...
9372                   31
7291                   19
17728                   5
7293                    6
17673                  31

[16000 rows x 1 columns]

In [ ]:
X_test

Acedamic percentage in Operating Systems percentage in Algorithms  \
19778                                 0.378806                 0.319218   
4376                                  0.340161                 0.269782   
10188                                 0.352512                 0.273197   
9887                                  0.356542                  0.37802   
4441                                  0.359401                 0.278108   
...                                        ...                      ...   
13123                                 0.298557                 0.319006   
18706                                 0.386445                 0.386445   
7274                                  0.385478                 0.360608   
16155                                  0.35411                 0.349993   
16712                                 0.275017                  0.30994   

      Percentage in Programming Concepts Percentage in Software Engineering  \
19778                           0.310706                           0.344756   
4376                            0.269782                            0.34407   
10188                           0.264384                           0.392169   
9887                            0.317881                           0.313585   
4441                            0.316615                           0.346565   
...                                  ...                                ...   
13123                           0.372173                           0.339455   
18706                           0.261785                             0.3906   
7274                            0.356463                           0.331594   
16155                           0.263524                           0.345875   
16712                           0.288113                           0.357959   

      Percentage in Computer Networks Percentage in Electronics Subjects  \
19778                         0.30645                           0.276656   
4376                          0.34798                            0.34798   
10188                        0.396576                           0.277603   
9887                         0.309289                           0.317881   
4441                         0.342287                           0.367958   
...                               ...                                ...   
13123                        0.265838                           0.380353   
18706                        0.274251                            0.31996   
7274                         0.364753                           0.327449   
16155                        0.341758                           0.255289   
16712                        0.288113                           0.388517   

      Percentage in Computer Architecture Percentage in Mathematics  \
19778                            0.344756                   0.30645   
4376                             0.340161                    0.3558   
10188                            0.405389                  0.304041   
9887                             0.313585                  0.399499   
4441                             0.316615                   0.33373   
...                                   ...                       ...   
13123                            0.359904                  0.351724   
18706                            0.282562                  0.282562   
7274                             0.344028                  0.248695   
16155                            0.349993                  0.378816   
16712                            0.344863                  0.392882   

      Percentage in Communication skills Hours working per day  ...  \
19778                           0.391574              0.021281  ...   
4376                             0.36753               0.01564  ...   
10188                           0.290822              0.030845  ...   
9887                            0.270628              0.017183  ...   
4441                            0.3